#define WIDTH   16
#define HEIGHT	18
#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480
#define GAMESPACE_WIDTH 20*WIDTH
#define GAMESPACE_HEIGHT 20*HEIGHT
#define X_OFFSET (SCREEN_WIDTH - 20*WIDTH)/2
#define Y_OFFSET (SCREEN_HEIGHT - 20*HEIGHT)/2
#define START_SPEED 300